export default {
  ITEM_CLICK: 'ITEM_CLICK',
  ITEM_CREATE: 'ITEM_CREATE',
  ITEM_DELETE: 'ITEM_DELETE',
  ITEM_EDIT_CANCEL: 'ITEM_EDIT_CANCEL',
  ITEM_EDIT_UPDATE: 'ITEM_EDIT_UPDATE',
  ITEM_SAVE: 'ITEM_SAVE',
};
